#
# Put your docker-compose configuration here and use it inside the container with the built
# int dc alias.
#


# -----------------------------------------
# Database sample
# -----------------------------------------
#sampleDb:
#  image: "amontaigu/mysql:5.6"
#  ports:
#    - "3306:3306"
#  environment:
#    MYSQL_ROOT_PASSWORD: pwd
#  volumes:
#    - ./docker/sample-db/init:/entrypoint-initdb.d
