version: 2

# =======================================================================
# JOBS definition
# =======================================================================
jobs:

# --------------------------------------------
# JOB: build docker application image
# --------------------------------------------
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.2-ce-git
        environment:
          DOCKER_APP_IMAGE_NAME_MASTER: amontaigu/replica-master
          DOCKER_APP_IMAGE_NAME_SLAVE: amontaigu/replica-slave
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - cache-v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
          paths:
            - /caches/docker_app_image_master.tar
            - /caches/docker_app_image_slave.tar
      - run:
          name: Load docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker_app_image_master.tar | true
            docker load -i /caches/docker_app_image_slave.tar | true
      - run:
          name: Build docker image
          command: |
            cd /app/master
            docker build --cache-from=$DOCKER_APP_IMAGE_NAME_MASTER --tag $DOCKER_APP_IMAGE_NAME_MASTER .
            cd /app/slave
            docker build --cache-from=$DOCKER_APP_IMAGE_NAME_SLAVE --tag $DOCKER_APP_IMAGE_NAME_SLAVE .
      - run:
          name: Save docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docker_app_image_master.tar $DOCKER_APP_IMAGE_NAME_MASTER
            docker save -o /caches/docker_app_image_slave.tar $DOCKER_APP_IMAGE_NAME_SLAVE
      - save_cache:
          key: cache-v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ epoch }}
          paths:
            - /caches/docker_app_image_master.tar
            - /caches/docker_app_image_slave.tar

# --------------------------------------------
# JOB: test docker application image
# --------------------------------------------
  test:
    working_directory: /app
    docker:
      - image: docker:17.06.2-ce-git
        environment:
          DOCKER_APP_IMAGE_NAME_MASTER: amontaigu/replica-master
          DOCKER_APP_IMAGE_NAME_SLAVE: amontaigu/replica-slave
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - cache-v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
          paths:
            - /caches/docker_app_image_master.tar
            - /caches/docker_app_image_slave.tar
      - run:
          name: Load docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker_app_image_master.tar | true
            docker load -i /caches/docker_app_image_slave.tar | true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              bats
      - run:
          name: Run tests
          command: |
            export UNISON_VERSION_MASTER="$(sed -nre 's/^.*UNISON_VERSION="([^"]+)".*$/\1/p;' /app/master/Dockerfile | head -1)"
            export UNISON_VERSION_SLAVE="$(sed -nre 's/^.*UNISON_VERSION="([^"]+)".*$/\1/p;' /app/slave/Dockerfile | head -1)"
            bats tests

# --------------------------------------------
# JOB: deploy docker application image
# --------------------------------------------
  deploy:
    working_directory: /app
    docker:
      - image: docker:17.06.2-ce-git
        environment:
          DOCKER_APP_IMAGE_NAME_MASTER: amontaigu/replica-master
          DOCKER_APP_IMAGE_NAME_SLAVE: amontaigu/replica-master
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - cache-v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
          paths:
            - /caches/docker_app_image_master.tar
            - /caches/docker_app_image_slave.tar
      - run:
          name: Load docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker_app_image_master.tar | true
            docker load -i /caches/docker_app_image_slave.tar | true
      - deploy:
          name: Push image to docker hub
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $DOCKER_APP_IMAGE_NAME_MASTER $DOCKER_APP_IMAGE_NAME_MASTER:$CIRCLE_TAG
              docker push $DOCKER_APP_IMAGE_NAME_MASTER:$CIRCLE_TAG
              docker tag $DOCKER_APP_IMAGE_NAME_SLAVE $DOCKER_APP_IMAGE_NAME_SLAVE:$CIRCLE_TAG
              docker push $DOCKER_APP_IMAGE_NAME_SLAVE:$CIRCLE_TAG
            fi


# =======================================================================
# WORKFLOWS definition
# =======================================================================
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
